[package]
name = "xed-sys2"
version = "0.1.0"
edition = "2021"
links = "xed"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69.1"
